### ISSUE TITLE
Differentiate the State of Command

### ISSUE THREAD

**Issue by teweitsai** [lsst-ts/ts_MTAOS#15]
Each command should be only executable in a specific state. I planned to put this idea into the Model class. I noticed that the ts_hexapod has the functions of assert_enabled_substate() and the similar things. Need to consider to use this one or follow the idea of component template by Paul.

**Comment by tribeiro** [comment]
Please, use the idea of `assert_enabled_substate()`....

**Comment by teweitsai** [comment]
Fixed in commit: 9cf5e7b. Use the summary state from salobj directly. Therefore, the judge of state can only be in CSC level.
